---
- name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
  win_updates:
    category_names: SecurityUpdates
    state: searched
    log_path: C:\ansible_wu.txt
  register: wsus

- name: Resultado da task anterior
  debug:
     msg: wsus